            - name: Github Issue Labeler
  # You may pin to the exact commit or the version.
  # uses: MaximilianAnzinger/issue-labeler@00977a029cf7d460956aa4d48af58a91a28c139a
  uses: MaximilianAnzinger/issue-labeler@1.0.2
  with:
    # The GITHUB_TOKEN secret
    repo-token: # optional, default is ${{ github.token }}
    # The path to the label configuration file. If the file doesn't exist at the specified path on the runner, action will read from the source repository via the Github API.
    configuration-path: 
    # Search for keywords in the title
    include-title: # optional, default is 1
    # Search for keywords in the body
    include-body: # optional, default is 1
    # The number of the issue to label
    issue-number: # optional, default is ${{ github.event.issue.number }}
          
